name: manage-azure-policy-80c4965b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'export/policies/Kubernetes_cluster_services_loadbalancers_should_listen_only_on_allowed_ports_9c7dd81e-ae40-46e9-bcda-ef1d5e0830ae/**'
#      - .github/workflows/manage-azure-policy-80c4965b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_80c4965b}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          export/policies/Kubernetes_cluster_services_loadbalancers_should_listen_only_on_allowed_ports_9c7dd81e-ae40-46e9-bcda-ef1d5e0830ae/**
